//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsole.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IVisitTrackService")]
    public interface IVisitTrackService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitTrackService/Visit", ReplyAction="http://tempuri.org/IVisitTrackService/VisitResponse")]
        bool Visit(string sysname, string modname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitTrackService/Visit2", ReplyAction="http://tempuri.org/IVisitTrackService/Visit2Response")]
        bool Visit2(string sysname, string modname, string memo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVisitTrackServiceChannel : TestConsole.ServiceReference1.IVisitTrackService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VisitTrackServiceClient : System.ServiceModel.ClientBase<TestConsole.ServiceReference1.IVisitTrackService>, TestConsole.ServiceReference1.IVisitTrackService {
        
        public VisitTrackServiceClient() {
        }
        
        public VisitTrackServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VisitTrackServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VisitTrackServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VisitTrackServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Visit(string sysname, string modname) {
            return base.Channel.Visit(sysname, modname);
        }
        
        public bool Visit2(string sysname, string modname, string memo) {
            return base.Channel.Visit2(sysname, modname, memo);
        }
    }
}
